/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        primary: '#FFC83B',
        'primary-dark': '#FFA000',
        secondary: '#F26522',
        accent: '#FF8C00',
        sunburst: '#FFF6DC',
        milk: '#FFFDF5',
        'milk-soft': '#FFF9EB',
        'milk-cream': '#FFF3D6',
        'milk-warm': '#FDEFD0',
        gold: '#FFC83B',
        'gold-bright': '#FFD54F',
        'gold-deep': '#FFA000',
        neon: '#F26522',
        mahogany: '#3A0808',
        'maroon-deep': '#140304',
        'maroon-dark': '#2B0808',
        'midnight-950': '#0D0404',
        'midnight-900': '#1A0405',
        espresso: '#1A0405',
        obsidian: '#0D0404',
        ivory: '#FFFDF5',
        cream: '#FFF3D6',
      },
      fontFamily: {
        syne: ['Syne', 'Montserrat', 'sans-serif'],
        display: ['Syne', 'Montserrat', 'sans-serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        sans: ['"Plus Jakarta Sans"', 'Montserrat', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        brush: ['Syne', 'Montserrat', 'sans-serif'],
        script: ['Syne', 'Montserrat', 'sans-serif'],
        atkinson: ['"Atkinson Hyperlegible"', 'sans-serif'],
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 5s ease-in-out infinite',
        'pulse-glow-slow': 'pulse-glow 8s ease-in-out infinite',
        shimmer: 'shimmer 2.5s infinite',
        rotate: 'rotate 28s linear infinite',
        'rotate-reverse': 'rotate-reverse 34s linear infinite',
        'bounce-slow': 'bounce-slow 2.2s ease-in-out infinite',
        waveform: 'waveform 1.2s ease-in-out infinite',
        'slow-pan': 'slow-pan 22s ease-in-out infinite alternate',
        'fade-in': 'fade-in 0.8s ease-out forwards',
        'fade-in-up': 'fade-in-up 0.8s ease-out forwards',
        'fade-in-scale': 'fade-in-scale 0.6s ease-out forwards',
        'scale-in': 'scale-in 0.6s ease-out forwards',
      },
      transitionDelay: {
        '50': '50ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
        '300': '300ms',
        '400': '400ms',
        '500': '500ms',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-16px)' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '0.45', filter: 'brightness(1)' },
          '50%': { opacity: '0.9', filter: 'brightness(1.25)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.35', transform: 'scale(1)' },
          '50%': { opacity: '0.75', transform: 'scale(1.08)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(200%)' },
        },
        rotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'rotate-reverse': {
          '0%': { transform: 'rotate(360deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        waveform: {
          '0%, 100%': { transform: 'scaleY(0.3)' },
          '50%': { transform: 'scaleY(1)' },
        },
        'slow-pan': {
          '0%': { transform: 'scale(1) translate(0)' },
          '100%': { transform: 'scale(1.08) translate(-1.5%, -1%)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-scale': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
};
